# Generated by Django 5.1 on 2025-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_multiskilling_notes_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('employee_registration', 'Employee Registration'), ('level_exam_completed', 'Level Exam Completed'), ('training_added', 'Training Added'), ('training_updated', 'Training Updated'), ('training_scheduled', 'Training Scheduled'), ('training_completed', 'Training Completed'), ('training_reschedule', 'Training Reschedule'), ('refresher_training_scheduled', 'Refresher Training Scheduled'), ('refresher_training_completed', 'Refresher Training Completed'), ('bending_training_added', 'Bending Training Added'), ('level_promotion', 'Level Promotion'), ('skill_matrix_updated', 'Skill Matrix Updated'), ('machine_allocated', 'Machine Allocated'), ('test_assigned', 'Test Assigned'), ('evaluation_completed', 'Evaluation Completed'), ('milestone_reached', 'Milestone Reached'), ('system_alert', 'System Alert')], max_length=50),
        ),
    ]
