# Generated by Django 5.1 on 2025-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiskilling',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='refreshment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
