# Generated by Django 5.0.6 on 2025-07-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_humanbodycheck_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='doj',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='sdcorientationfeedback',
            name='trainee_name',
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='temp_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sdcorientationfeedback',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='orientation_feedbacks', to='app1.userinfo'),
        ),
    ]
