# Generated by Django 5.1 on 2025-07-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_sdcorientationfeedback_doj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiskilling',
            old_name='end_date',
            new_name='date_of_join',
        ),
        migrations.RenameField(
            model_name='multiskilling',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='multiskilling',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='multiskilling',
            name='refreshment_date',
        ),
        migrations.RemoveField(
            model_name='multiskilling',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='multiskilling',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='operatorlevel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='operatorlevel',
            name='remarks',
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='employee_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='multiskilling',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='operatorlevel',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MonthlySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiskilling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_skills', to='app1.multiskilling')),
                ('operator_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_skills', to='app1.operatorlevel')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlySkillEvaluation',
        ),
    ]
