# Generated by Django 5.1.3 on 2025-07-19 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_end_date_multiskilling_date_of_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.level'),
        ),
        migrations.AlterField(
            model_name='score',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.station'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.level'),
        ),
    ]
